# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mazo_de_cartas', jsonfield.fields.JSONField(default=b'{"cartas": {"c36": null, "c40": null, "c37": null, "c47": null, "c41": null, "c19": null, "c18": null, "c39": null, "c38": null, "c13": null, "c12": null, "c11": null, "c10": null, "c17": null, "c16": null, "c15": null, "c14": null, "c44": null, "c42": null, "c45": null, "c46": null, "c35": null, "c9": null, "c8": null, "c34": null, "c3": null, "c2": null, "c1": null, "c0": null, "c7": null, "c6": null, "c5": null, "c4": null, "c22": null, "c23": null, "c20": null, "c21": null, "c26": null, "c27": null, "c24": null, "c25": null, "c31": null, "c28": null, "c29": null, "c48": null, "c49": null, "c30": null, "c33": null, "c43": null, "c32": null}, "nombre": null, "utilizable": false}', editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
